name: Deploy to Staging

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      uses: actions/checkout@v2
      with:
        ref: develop
    - id: deploy
      uses: GoogleCloudPlatform/github-actions/appengine-deploy@master
      with:
        credentials: ${{ secrets.gcp_credentials }}
        deliverables: ../app/app.yaml
        version: staging
        promote: false
