name: Deploy to Staging

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      uses: actions/checkout@v2
      with:
        ref: develop
    - id: setup-env-variables
      uses: bluwy/substitute-string-action@v1
      with:
        _input-file: ./app/env_variables.yaml
        _output-file: ./app/env_variables.yaml
        _format-key: '%%key%%'
        SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
        SESSION_LENGTH: ${{ secrets.SESSION_LENGTH }}
        ELASTICSEARCH_DOMAIN: ${{ secrets.ELASTICSEARCH_DOMAIN }}
        ELASTICSEARCH_USERNAME: ${{ secrets.ELASTICSEARCH_USERNAME }}
        ELASTICSEARCH_PASSWORD: ${{ secrets.ELASTICSEARCH_PASSWORD }}
        DATASTORE_PROJECT_ID: ${{ secrets.DATASTORE_PROJECT_ID }}
        LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
    - id: deploy
      uses: GoogleCloudPlatform/github-actions/appengine-deploy@master
      with:
        credentials: ${{ secrets.gcp_credentials }}
        deliverables: ./app/app.yaml
        version: staging
        promote: false
